language: python
python:
  - "3.7-dev"
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - "pypy"
  - "pypy3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install --upgrade tox-travis

# command to run tests, e.g. python setup.py test
script: tox
