language: python
python:
  - "3.7-dev"
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - "pypy2-5.7.1"
  - "pypy3.5-5.8.0"
    # "pypy" (short version) is deprecated but not documented as such:
    # see https://github.com/travis-ci/travis-cookbooks/pull/861
    # and https://github.com/travis-ci/travis-ci/issues/6865

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install --upgrade tox-travis

# command to run tests, e.g. python setup.py test
script: tox
